import Head from 'next/head';

const Airtable = require('airtable');

export default function Home({ data }) {
  return (
    <div className="w-fit flex flex-col gap-8">
      <Head>
        <title>Invoice Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {data}
    </div>
  );
}

export const getStaticProps = async (ctx) => {
  const base = new Airtable({
    apiKey: process.env.AIRTABLE_API_KEY,
  }).base(process.env.AIRTABLE_BASE_ID);

  const table = base(process.env.AIRTABLE_CLIENTS_TABLE);

  const records = await table.select().all();

  const data = await JSON.stringify(records);

  return {
    props: {
      data,
    },
  };
};
