import Head from 'next/head';
import Link from 'next/link';

import InvoiceCardSummary from '../modules/Invoice/InvoiceCardSummary';
import * as Button from '../components/Button';

import { getClientsTable } from '../lib/airtable';

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Invoice Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full flex justify-between items-center">
        <div className="flex flex-col gap-1">
          <h2>Invoices</h2>
          <span className="body--1 text-blue-lighter">{data.length} invoices</span>
        </div>

        <div className="flex items-center gap-5">
          <div className="flex items-center gap-2">
            <span className="font-bold body--1 text-black-shade">Filter</span>
            <span className="text-violet-normal">
              <svg width="11" height="7" xmlns="http://www.w3.org/2000/svg">
                <path
                  d="M1 1l4.228 4.228L9.456 1"
                  stroke="#7C5DFA"
                  strokeWidth="2"
                  fill="none"
                  fillRule="evenodd"
                />
              </svg>
            </span>
          </div>

          <Button.Add text="New" />
        </div>
      </div>

      <section className="flex flex-col gap-4">
        {data
          ? data.map((invoice) => (
              <Link
                className="hidden"
                key={invoice.invoice_id}
                href={'/invoice/' + invoice.invoiced}>
                <a>
                  <InvoiceCardSummary {...invoice} />
                </a>
              </Link>
            ))
          : console.log('there is an error')}
      </section>
    </>
  );
}

export const getServerSideProps = async (ctx) => {
  const records = await getClientsTable();

  return {
    props: {
      data: JSON.parse(JSON.stringify(records)).map((record) => record.fields),
    },
  };
};
